# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-11-09 06:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_studyrecord'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='branch',
            options={'verbose_name': '校区表', 'verbose_name_plural': '校区表'},
        ),
        migrations.AlterModelOptions(
            name='classlist',
            options={'verbose_name': '班级信息表', 'verbose_name_plural': '班级信息表'},
        ),
        migrations.AlterModelOptions(
            name='course',
            options={'verbose_name': '课程表', 'verbose_name_plural': '课程表'},
        ),
        migrations.AlterModelOptions(
            name='courserecord',
            options={'verbose_name': '上课记录表', 'verbose_name_plural': '上课记录表'},
        ),
        migrations.AlterModelOptions(
            name='customer',
            options={'verbose_name': '客户表', 'verbose_name_plural': '客户表'},
        ),
        migrations.AlterModelOptions(
            name='customerfollowup',
            options={'verbose_name': '客户跟进表', 'verbose_name_plural': '客户跟进表'},
        ),
        migrations.AlterModelOptions(
            name='enrollment',
            options={'verbose_name': '报名表(学生表)', 'verbose_name_plural': '报名表(学生表)'},
        ),
        migrations.AlterModelOptions(
            name='payment',
            options={'verbose_name': '缴费记录表', 'verbose_name_plural': '缴费记录表'},
        ),
        migrations.AlterModelOptions(
            name='role',
            options={'verbose_name': '角色表', 'verbose_name_plural': '角色表'},
        ),
        migrations.AlterModelOptions(
            name='studyrecord',
            options={'verbose_name': '学习记录表', 'verbose_name_plural': '学习记录表'},
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={'verbose_name': '客户状态标签表', 'verbose_name_plural': '客户状态标签表'},
        ),
        migrations.AlterModelOptions(
            name='userprofile',
            options={'verbose_name': '账户表', 'verbose_name_plural': '账户表'},
        ),
        migrations.AlterUniqueTogether(
            name='studyrecord',
            unique_together=set([('student', 'course_record')]),
        ),
    ]
