# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-11-09 06:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_auto_20181109_1450'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='tags',
            new_name='status',
        ),
    ]
