# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-11-09 07:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_auto_20181109_1453'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='status',
            new_name='tags',
        ),
    ]
